# Wybierz obraz podstawowy z Pythonem
FROM python:3.11-slim

# Ustaw katalog roboczy w kontenerze
WORKDIR /app

# Skopiuj pliki do kontenera
COPY . /app

# Instalacja zależności
RUN pip install --no-cache-dir -r requirements.txt

# Eksponuj port, na którym działa aplikacja
EXPOSE 5000

# Polecenie do uruchomienia aplikacji
CMD ["python", "freddy_fazber.py"]