# Choose a base image with Python
FROM python:3.11-slim

# Install necessary build dependencies and tools
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    musl-dev \
    libffi-dev \
    libssl-dev \
    libaio-dev \
    libssl-dev \
    unzip \
    libaio1 \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy all files to the container
COPY . /app

# Install dependencies using pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Expose the port where the application runs
EXPOSE 5000

# Command to run the application
CMD ["python", "freddy_fazber.py"]